### ISSUE TITLE
License for Runtime

### ISSUE THREAD

**Issue by 0x10bit** [1Kuso4ek1/3Dev#23]
I would like to use this engine in one of my projects.

Is the 3Dev runtime under a different license, or is the entire project (Editor + Runtime) GPL license only?

**Comment by 1Kuso4ek1** [comment]
Hello. Everything is under GPL, feel free to use it 🤗
And by the way, can you leave a link to your project?

**Comment by 0x10bit** [comment]
Yes, when it is finished, I will provide a link to it.
