### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [1Kuso4ek1/3Dev#9]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [Renderer::DeleteInstance](https://github.com/1Kuso4ek1/3Dev/blob/b2ac1ebeb4f6396b66d834ee361037f7b80fb4ad/3Dev/src/Renderer.cpp#L16 "Renderer::DeleteInstance function")
- [TextureManager::DeleteInstance](https://github.com/1Kuso4ek1/3Dev/blob/ee4ecf2a405281b19e0080fe19e2d0aeb4eef99d/3Dev/src/TextureManager.cpp#L17 "TextureManager::DeleteInstance function")

**Comment by 1Kuso4ek1** [comment]
Done :+1:

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/1Kuso4ek1/3Dev/commit/185c4764ffb98e041a746ffe274bedfb55e2398e "Removed null pointer checks").
